### ISSUE TITLE
Crashes during updatetools

### ISSUE THREAD

**Issue by wbwkx** [ThomasTJdev/WMD#1]
## 1. sys info 
```
Python 3.5.0
macos 10.12.2
Darwin baidapang.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

## 2. step to it
```
1. up with root
2. updatetools
3. wait seconds after all tools checked.
```

## 3. logs
```
Traceback (most recent call last):
  File "wmd.py", line 242, in <module>
    main()
  File "wmd.py", line 236, in main
    console(path)
  File "wmd.py", line 172, in console
    updatetools()
  File "wmd.py", line 78, in updatetools
    ctools.clonegits('u')
  File "/Users/wuten/WMD/core/tools.py", line 165, in clonegits
    os.mknod(updatefile)
OSError: [Errno 22] Invalid 
```

Touch a lastupdate.txt is no need in my opinion.
```python 
updatefile = 'logs/lasttoolupdate.txt'
    # if not os.path.isfile(updatefile):
        # os.mknod(updatefile)
    with open(updatefile, 'w') as file:
        file.write(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
```

**Comment by ThomasTJdev** [comment]
Hi @wbwkx 

Thank you for the detailed issue description!

1. The tool is developed on a Linux box (ARCH). WMD is not tested on Mac devices. The README.md is updated with Linux as a requirement in commit @b09ac97.
2. You are completely right regarding your code suggestion for the "lasttoolsupdate.txt". I have removed the code according to your suggestion @3ba66a1. Thank you!

Would you mind try again?

**Comment by ThomasTJdev** [comment]
Closed - no feedback
